/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import reglanegocio.Usuario;
import presentacion.FrmPrincipal;
//import static presentacion.FrmPrincipal.txtUsernameP;

/**
 *
 * @author lzuluaga
 */
public class FrmHistorial2 extends javax.swing.JFrame {

    /**
     * Creates new form FrmHistorial2
     */
    
    DefaultTableModel modelo;
    String datos[] = new String[4];
    public static String dato;
    
    public FrmHistorial2(String username) throws SQLException  {
        initComponents();
         Usuario Usuario;
        txtUsernameH.setText(dato);

        //   cargarDatos();
        modelo = new DefaultTableModel();

        modelo.addColumn("Celular");
        modelo.addColumn("Operador");
        modelo.addColumn("Monto");
        this.Tabla.setModel(modelo);
    }

    FrmHistorial2() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        txtUsernameH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 140, 460, 130));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        txtUsernameH.setEditable(false);
        getContentPane().add(txtUsernameH, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        boolean reg = false;

        var usu = new Usuario();

        String vUsername;

        vUsername = txtUsernameH.getText();
        //vFecha = fun.getFecha(jdcFecha);
        //idM =Integer.parseInt(txtB.getText()) ;
        try {
            reg = usu.ConsultarHistorial(vUsername);

        } catch (SQLException ex) {
            Logger.getLogger(FrmHistorial.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (reg == true) {

            datos[0] = usu.getCelular();
            datos[1] = usu.getOperador();
            datos[2] = String.valueOf(usu.getMonto());
            modelo.addRow(datos);
        } else {

            JOptionPane.showMessageDialog(null, "no");
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHistorial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHistorial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHistorial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHistorial2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHistorial2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtUsernameH;
    // End of variables declaration//GEN-END:variables
}
