/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import reglanegocio.Usuario;
import presentacion.FrmPrincipal;


/**
 *
 * @author LEONARDO
 */
public class FrmHistorial extends javax.swing.JFrame {

    /**
     * Creates new form FrmHistorial
     */
    DefaultTableModel modelo;
    String datos[] = new String[4];
    public static String dato;

    public FrmHistorial(String username) throws SQLException {
        initComponents();
        Usuario Usuario;
        txtUsernameH.setText(dato);

        //   cargarDatos();
        modelo = new DefaultTableModel();

        modelo.addColumn("Celular");
        modelo.addColumn("Operador");
        modelo.addColumn("Monto");
        this.Tabla.setModel(modelo);

    }

    FrmHistorial() {

    }

//    private void cargarDatos() {
//        boolean reg = false;
//
//        var usu = new Usuario();
//        //var fun = new FuncionesCalendar();
//
//        String username = usu.getUsername();
//
//        //vFecha = ((JTextField) jdcFecha.getDateEditor().getUiComponent()).getText();
//        //vFecha = fun.getFecha(jdcFecha);
//        //idM =Integer.parseInt(txtB.getText()) ;
//        try {
//            reg = usu.ConsultarHistorial(username);
//
//        } catch (SQLException ex) {
//            Logger.getLogger(FrmHistorial.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        if (reg == true) {
//            datos[0] = usu.getCelular();
//            datos[1] = usu.getOperador();
//            datos[2] = String.valueOf(usu.getMonto());
//            modelo.addRow(datos);
//        } else {
//
//            JOptionPane.showMessageDialog(null, "No hay historial de recargas.");
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        txtUsernameH = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 102, 255));
        jLabel7.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Historial de Recargas");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 30));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 140, 460, 130));

        txtUsernameH.setEditable(false);
        jPanel1.add(txtUsernameH, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 230, -1));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel1.setText("HOLAA!!!!!!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        boolean reg = false;

        var usu = new Usuario();

        String vUsername;

        vUsername = txtUsernameH.getText();
        //vFecha = fun.getFecha(jdcFecha);
        //idM =Integer.parseInt(txtB.getText()) ;
        try {
            reg = usu.ConsultarHistorial(vUsername);

        } catch (SQLException ex) {
            Logger.getLogger(FrmHistorial.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (reg == true) {

            datos[0] = usu.getCelular();
            datos[1] = usu.getOperador();
            datos[2] = String.valueOf(usu.getMonto());
            modelo.addRow(datos);
        } else {

            JOptionPane.showMessageDialog(null, "Usted no tiene citas asociadas para el dia seleccionado");
        }


    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHistorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHistorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtUsernameH;
    // End of variables declaration//GEN-END:variables

    private static class pr {

        public pr() {
        }
    }
}
