
package presentacion;

import Procesos.Procesos;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import reglanegocio.Usuario;
import Procesos.TextPrompt;
import java.awt.Color;

public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        txtUsername.requestFocus();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo-nequi-principal.png")));
        //Placeholders
        TextPrompt toTxtUsername = new TextPrompt("Ingresa tu username", txtUsername);
        TextPrompt toTxtPassword = new TextPrompt("Ingresa tu clave", txtPassword);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        btnSalir1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        icono = new javax.swing.JLabel();
        btnEntraPng = new javax.swing.JLabel();
        lblNequiTitulo = new javax.swing.JLabel();
        lblBy = new javax.swing.JLabel();
        lblMade = new javax.swing.JLabel();
        lblAyuda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(35, 28, 70));
        jPanel8.setForeground(new java.awt.Color(0, 204, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir1.setBackground(new java.awt.Color(204, 0, 51));
        btnSalir1.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("X");
        btnSalir1.setBorder(null);
        btnSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 50, 33));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(35, 28, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBackground(new java.awt.Color(62, 32, 96));
        txtUsername.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setToolTipText("");
        txtUsername.setBorder(null);
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 280, 30));
        txtUsername.getAccessibleContext().setAccessibleName("");

        txtPassword.setBackground(new java.awt.Color(62, 32, 96));
        txtPassword.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 280, 30));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-nequi-3.png"))); // NOI18N
        jPanel2.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 240, 230));

        btnEntraPng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/entra.png"))); // NOI18N
        btnEntraPng.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntraPng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntraPngMouseClicked(evt);
            }
        });
        jPanel2.add(btnEntraPng, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 490, -1, -1));

        lblNequiTitulo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblNequiTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblNequiTitulo.setText("NEQUI");
        jPanel2.add(lblNequiTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        lblBy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBy.setForeground(new java.awt.Color(255, 255, 255));
        lblBy.setText("< / >");
        lblBy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblByMouseClicked(evt);
            }
        });
        jPanel2.add(lblBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, -1, 30));

        lblMade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMade.setForeground(new java.awt.Color(255, 255, 255));
        lblMade.setText("Made with ♥ by Leonardo Zuluaga");
        lblMade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMadeMouseExited(evt);
            }
        });
        jPanel2.add(lblMade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 300, 30));

        lblAyuda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAyuda.setForeground(new java.awt.Color(255, 255, 255));
        lblAyuda.setText("Ayuda");
        lblAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAyudaMouseClicked(evt);
            }
        });
        jPanel2.add(lblAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 587, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        Procesos proc = new Procesos();        
        proc.validarCaracteresNumeros(evt);
    }//GEN-LAST:event_txtUsernameKeyTyped
    
    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        Procesos proc = new Procesos();        
        proc.validarCaracteresNumeros(evt);
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void btnEntraPngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntraPngMouseClicked
        String vUsername = txtUsername.getText();
        String vPassword = new String(txtPassword.getPassword());
        var permitir = false;
        var usu = new Usuario();
        try {
            permitir = usu.permitirAcceso(vUsername, vPassword);
            if (permitir) {
                if (usu.getIdTipoUsuario() == 1) {
                    //var frm = new FrmUsuario();
                    var frm = new FrmPrincipal(usu);
                    frm.setVisible(true);
                }else if (usu.getIdTipoUsuario() == 2) {
                    //instancia formulario del admin
                }else if (usu.getIdTipoUsuario() == 3) {
                    //instancia formulario usuario limitado
                }
                this.dispose();
            }
            else{
                if (usu.getIdEstado() == 0) {
                    JOptionPane.showMessageDialog(null, "El nombre de usuario o contraseña no son validos");
                }else if (usu.getIdEstado() == 2) {
                    JOptionPane.showMessageDialog(null, "El usuario se encuentra inactivo");
                }else if (usu.getIdEstado() == 3) {
                    JOptionPane.showMessageDialog(null, "El usuario se encuentra bloqueado");
                }else if (usu.getIdEstado() == 4) {
                    JOptionPane.showMessageDialog(null, "El usuario se encuentra retirado");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEntraPngMouseClicked

    private void lblByMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblByMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://www.leonardozuluaga.com.co"));
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_lblByMouseClicked

    private void lblMadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMadeMouseClicked

    private void lblAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAyudaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAyudaMouseClicked

    private void lblMadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMadeMouseExited
        //lblMade.setBackground(Color.red);
        lblMade.setForeground(Color.white);
    }//GEN-LAST:event_lblMadeMouseExited

    private void lblMadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMadeMouseEntered
        lblMade.setForeground(Color.GRAY);
    }//GEN-LAST:event_lblMadeMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEntraPng;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel icono;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblBy;
    public javax.swing.JLabel lblMade;
    private javax.swing.JLabel lblNequiTitulo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
