package presentacion;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import reglanegocio.Usuario;
import reglanegocio.Operador;
import Procesos.Procesos;
import Procesos.TextPrompt;
import Procesos.PanelRound;
import java.awt.Color;
import java.awt.Toolkit;

public class FrmPrincipal extends javax.swing.JFrame {

    public FrmPrincipal(Usuario u) throws SQLException {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo-nequi-2.png")));
        //set en info
        txtNombreP.setText(u.getNombre());
        txtUsernameP.setText(u.getUsername());
        txtSaldoP.setText(String.valueOf(u.getSaldo()));
        //Set msj bienvenido
        lblBienvenida.setText("Hola,");
        lblBienvenida2.setText(u.getNombre());
        lblSaldo.setText("$ "+String.valueOf(u.getSaldo()));
        txtUserBuscar.setText(txtUsernameP.getText());

        //cargar operadores
        cargarComboOperador();
        
        //Placeholder Enviar
        TextPrompt toTxtUsername = new TextPrompt("Username", txtUsernameR);
        TextPrompt toTxtMonto = new TextPrompt("¿Cuanto?", txtMontoR);
        TextPrompt toTxtAreaMensaje = new TextPrompt("Mensaje", txtAreaMensajeR);
    }

    public FrmPrincipal() {

    }

    private void cargarComboOperador() throws SQLException {
        Operador.cargarCombo(cmbOperadorRC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tbPrincipal = new javax.swing.JTabbedPane();
        ifInformacion = new javax.swing.JInternalFrame();
        lblDisponible = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        lblBienvenida2 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblLogoIcono = new javax.swing.JLabel();
        lblFranja = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSaldoP = new javax.swing.JTextField();
        lblBotonPeso = new javax.swing.JLabel();
        lblMarranito = new javax.swing.JLabel();
        lblMetas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ifOpciones = new javax.swing.JInternalFrame();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tbMenu = new javax.swing.JTabbedPane();
        ifEnviarDinero = new javax.swing.JInternalFrame();
        btnEnviarDinero = new javax.swing.JButton();
        txtUsernameR = new javax.swing.JTextField();
        txtMontoR = new javax.swing.JTextField();
        lblMsj1 = new javax.swing.JLabel();
        lblAvisoUsername = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaMensajeR = new javax.swing.JTextArea();
        ifRecargarSM = new javax.swing.JInternalFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCelularRC = new javax.swing.JTextField();
        txtCuantoRC = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnRecargar = new javax.swing.JButton();
        lblMsj = new javax.swing.JLabel();
        cmbOperadorRC = new javax.swing.JComboBox<>();
        lblContador = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnActua = new javax.swing.JButton();
        txtUserBuscar = new javax.swing.JTextField();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        lblNombre = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtUsernameP = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPrincipal.setBackground(new java.awt.Color(231, 59, 122));
        tbPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        tbPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbPrincipal.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N

        ifInformacion.setBackground(new java.awt.Color(255, 255, 255));
        ifInformacion.setVisible(true);
        ifInformacion.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDisponible.setBackground(new java.awt.Color(0, 102, 255));
        lblDisponible.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        lblDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblDisponible.setText("Disponible");
        ifInformacion.getContentPane().add(lblDisponible, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        lblBienvenida.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        ifInformacion.getContentPane().add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, 20));

        lblBienvenida2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBienvenida2.setForeground(new java.awt.Color(255, 255, 255));
        ifInformacion.getContentPane().add(lblBienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 230, 20));

        lblSaldo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ifInformacion.getContentPane().add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 270, 60));

        lblLogoIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-mini.png"))); // NOI18N
        lblLogoIcono.setRequestFocusEnabled(false);
        ifInformacion.getContentPane().add(lblLogoIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblFranja.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/forma.png"))); // NOI18N
        ifInformacion.getContentPane().add(lblFranja, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -190, 820, 410));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/forma2.png"))); // NOI18N
        ifInformacion.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-440, -80, 660, 360));

        txtSaldoP.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        txtSaldoP.setForeground(new java.awt.Color(0, 0, 0));
        txtSaldoP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSaldoP.setBorder(null);
        txtSaldoP.setEnabled(false);
        ifInformacion.getContentPane().add(txtSaldoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 40));

        lblBotonPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/button-peso.png"))); // NOI18N
        lblBotonPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBotonPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonPesoMouseClicked(evt);
            }
        });
        ifInformacion.getContentPane().add(lblBotonPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 80, 90));

        lblMarranito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marranito.png"))); // NOI18N
        lblMarranito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ifInformacion.getContentPane().add(lblMarranito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 50, 40));

        lblMetas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblMetas.setForeground(new java.awt.Color(26, 21, 53));
        lblMetas.setText("Metas");
        lblMetas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ifInformacion.getContentPane().add(lblMetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colchon.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ifInformacion.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 40, 50));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(26, 21, 53));
        jLabel11.setText("Colchón");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ifInformacion.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-product.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ifInformacion.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 40, 50));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(26, 21, 53));
        jLabel13.setText("Bolsillos");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ifInformacion.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, 30));

        tbPrincipal.addTab("Home", ifInformacion);

        ifOpciones.setBackground(new java.awt.Color(255, 255, 255));
        ifOpciones.setBorder(null);
        ifOpciones.setVisible(true);
        ifOpciones.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(26, 21, 53));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 102, 255));
        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menu Opciones");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        ifOpciones.getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 50));

        tbMenu.setBackground(new java.awt.Color(231, 59, 122));
        tbMenu.setForeground(new java.awt.Color(255, 255, 255));
        tbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbMenu.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N

        ifEnviarDinero.setBackground(new java.awt.Color(255, 255, 255));
        ifEnviarDinero.setBorder(null);
        ifEnviarDinero.setVisible(true);
        ifEnviarDinero.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviarDinero.setBackground(new java.awt.Color(231, 59, 122));
        btnEnviarDinero.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        btnEnviarDinero.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarDinero.setText("Enviar");
        btnEnviarDinero.setBorder(null);
        btnEnviarDinero.setBorderPainted(false);
        btnEnviarDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarDineroMouseClicked(evt);
            }
        });
        btnEnviarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarDineroActionPerformed(evt);
            }
        });
        btnEnviarDinero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEnviarDineroKeyPressed(evt);
            }
        });
        ifEnviarDinero.getContentPane().add(btnEnviarDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 300, 30));

        txtUsernameR.setBackground(new java.awt.Color(246, 246, 246));
        txtUsernameR.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        txtUsernameR.setForeground(new java.awt.Color(0, 0, 0));
        txtUsernameR.setBorder(null);
        txtUsernameR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameRKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameRKeyTyped(evt);
            }
        });
        ifEnviarDinero.getContentPane().add(txtUsernameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 300, 30));

        txtMontoR.setBackground(new java.awt.Color(246, 246, 246));
        txtMontoR.setFont(new java.awt.Font("Cascadia Mono", 0, 14)); // NOI18N
        txtMontoR.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoR.setBorder(null);
        txtMontoR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMontoRKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoRKeyTyped(evt);
            }
        });
        ifEnviarDinero.getContentPane().add(txtMontoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 300, 30));

        lblMsj1.setFont(new java.awt.Font("Cascadia Mono", 2, 10)); // NOI18N
        lblMsj1.setForeground(new java.awt.Color(102, 102, 102));
        lblMsj1.setText("La transferencia debe ser minimo de $5000 COP");
        ifEnviarDinero.getContentPane().add(lblMsj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 300, -1));

        lblAvisoUsername.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblAvisoUsername.setForeground(new java.awt.Color(204, 0, 0));
        ifEnviarDinero.getContentPane().add(lblAvisoUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 300, 20));

        jLabel8.setBackground(new java.awt.Color(0, 102, 255));
        jLabel8.setFont(new java.awt.Font("Cascadia Mono", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 21, 53));
        jLabel8.setText("Envía Plata");
        ifEnviarDinero.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        txtAreaMensajeR.setBackground(new java.awt.Color(246, 246, 246));
        txtAreaMensajeR.setColumns(20);
        txtAreaMensajeR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtAreaMensajeR.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaMensajeR.setRows(5);
        txtAreaMensajeR.setBorder(null);
        jScrollPane2.setViewportView(txtAreaMensajeR);

        ifEnviarDinero.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 300, 110));

        tbMenu.addTab("Enviar Plata", ifEnviarDinero);

        ifRecargarSM.setBackground(new java.awt.Color(255, 255, 255));
        ifRecargarSM.setBorder(null);
        ifRecargarSM.setVisible(true);
        ifRecargarSM.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 102, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 102, 255));
        jLabel7.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Recargar Celular");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 30));

        ifRecargarSM.getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        lblCelular.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(51, 51, 51));
        lblCelular.setText("Celular");
        ifRecargarSM.getContentPane().add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Operador");
        ifRecargarSM.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("¿Cuanto?");
        ifRecargarSM.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        txtCelularRC.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtCelularRC.setForeground(new java.awt.Color(0, 102, 255));
        txtCelularRC.setBorder(null);
        txtCelularRC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCelularRCKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCelularRCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularRCKeyTyped(evt);
            }
        });
        ifRecargarSM.getContentPane().add(txtCelularRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 300, 20));

        txtCuantoRC.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtCuantoRC.setForeground(new java.awt.Color(0, 102, 255));
        txtCuantoRC.setBorder(null);
        txtCuantoRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuantoRCActionPerformed(evt);
            }
        });
        txtCuantoRC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCuantoRCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuantoRCKeyTyped(evt);
            }
        });
        ifRecargarSM.getContentPane().add(txtCuantoRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 300, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        ifRecargarSM.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 300, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 255));
        ifRecargarSM.getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 300, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator4.setForeground(new java.awt.Color(0, 51, 255));
        ifRecargarSM.getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 300, 10));

        btnRecargar.setBackground(new java.awt.Color(0, 102, 255));
        btnRecargar.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecargar.setText("Recargar");
        btnRecargar.setBorder(null);
        btnRecargar.setBorderPainted(false);
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        ifRecargarSM.getContentPane().add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 300, 30));

        lblMsj.setFont(new java.awt.Font("Cascadia Mono", 2, 10)); // NOI18N
        lblMsj.setForeground(new java.awt.Color(102, 102, 102));
        lblMsj.setText("La recarga debe ser minimo de $1000 COP");
        ifRecargarSM.getContentPane().add(lblMsj, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 300, -1));

        cmbOperadorRC.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        cmbOperadorRC.setBorder(null);
        ifRecargarSM.getContentPane().add(cmbOperadorRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 166, 300, 30));

        lblContador.setForeground(new java.awt.Color(255, 51, 51));
        ifRecargarSM.getContentPane().add(lblContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 20));

        tbMenu.addTab("Recargar Celular", ifRecargarSM);

        jInternalFrame1.setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 102, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 102, 255));
        jLabel10.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Historial");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 40));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 40));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 70, 420, 260));

        btnActua.setText("actualizar");
        btnActua.setBorder(null);
        btnActua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnActua, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        txtUserBuscar.setEditable(false);
        jPanel2.add(txtUserBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 70, -1));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        tbMenu.addTab("Historial", jInternalFrame1);

        ifOpciones.getContentPane().add(tbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 620, 530));

        tbPrincipal.addTab("Opciones", ifOpciones);

        jInternalFrame2.setVisible(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Cascadia Mono", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cerrar Sesion");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 90, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator6.setForeground(new java.awt.Color(0, 51, 255));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 340, 10));

        lblNombre.setBackground(new java.awt.Color(0, 102, 255));
        lblNombre.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 102, 255));
        lblNombre.setText("Nombre");
        jPanel3.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        txtNombreP.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        txtNombreP.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreP.setEnabled(false);
        jPanel3.add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 340, 20));

        lblUsername.setBackground(new java.awt.Color(0, 102, 255));
        lblUsername.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 102, 255));
        lblUsername.setText("Username");
        jPanel3.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        txtUsernameP.setFont(new java.awt.Font("Cascadia Mono", 0, 18)); // NOI18N
        txtUsernameP.setForeground(new java.awt.Color(0, 0, 0));
        txtUsernameP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsernameP.setEnabled(false);
        jPanel3.add(txtUsernameP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 340, 20));

        jSeparator7.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator7.setForeground(new java.awt.Color(0, 51, 255));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 340, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator5.setForeground(new java.awt.Color(0, 51, 255));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 340, 10));

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbPrincipal.addTab("Configuraciones", jInternalFrame2);

        jPanel1.add(tbPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuaActionPerformed
        //        boolean reg = false;
        //
        //        var usu = new Usuario();
        //
        //        String vUsername = txtUsername.getText();
        //
        //        try {
            //            reg = usu.consultarhr(vUsername);
            //        } catch (SQLException ex) {
            //            Logger.getLogger(FrmHistorial.class.getName()).log(Level.SEVERE, null, ex);
            //        }
        //        if (reg == true) {
            //        model.addColumn("Username");
            //        model.addColumn("Celular");
            //        model.addColumn("idOperador");
            //        model.addColumn("Monto");
            //
            //        Tabla.setModel(model);
            //            datos[0] = usu.getNombre();
            //            datos[1] = usu.getCelular();
            //            datos[2] = usu.getOperador();
            //            datos[3] = String.valueOf(usu.getMonto());
            //            model.addRow(datos);
            //        } else {
            //            JOptionPane.showMessageDialog(null, "No hay datos");
            //        }
    }//GEN-LAST:event_btnActuaActionPerformed

//--------------------------------------------------------------------
//     BOTON PARA RECARGAR
//--------------------------------------------------------------------
    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        //Variables
        boolean consultaSaldo = false, consultaSaldoInicial = false;
        int numReg = 0;
        int idOperador;
        String usernameP, celular, montoR;
        double saldoP = 0, montoDoubleR = 0, monto = 0, saldoInicial = 0, restarSaldoPrincipal = 0;

        //Instancia usuario logeado principal
        var up = new Usuario();

        //User logeado realiza recarga $
        usernameP = txtUsernameP.getText();

        //Celular a realizarle recarga $
        celular = txtCelularRC.getText();

        //Operador escogido en el select para la recarga $
        idOperador = 0;

        //Variable montoR para guardar
        montoR = txtCuantoRC.getText();

        //Try para extraer saldo inicial del usuario P
        try {
            consultaSaldoInicial = up.consultarSaldo(usernameP);
            if (consultaSaldoInicial) {
                //Guardo el saldo inicial del usuario P
                saldoInicial = up.getSaldo();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        //Reset el select operador
        if ((cmbOperadorRC.getSelectedIndex() != -1)) {
            idOperador = cmbOperadorRC.getItemAt(cmbOperadorRC.getSelectedIndex()).getId();
        }
        //Valido que el celular este vacio
        if (txtCelularRC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo 'celular' esta vacio.");
        } //Valido que el operador haya sido escogido
        else if (cmbOperadorRC.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Escoge un operador");

            //Valido que monto sea mayor o este vacio
        } else if (txtCuantoRC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo 'cuanto' esta vacio, ingresa datos. \n"
                + "y el valor a recargar debe ser de 1000 COP en adelante.");

            //Valido que el monto sea menor a saldoInicial
        } else if (monto > saldoInicial) {
            JOptionPane.showMessageDialog(null, "No tiene saldo suficiente.");
        } else {
            try {
                consultaSaldo = up.consultarSaldo(usernameP);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            //Primer if
            if (consultaSaldo) {
                //Saldo del usuario principal que envia o recarga
                saldoP = up.getSaldo();
                //parseo de saldo y proceso resta
                try {
                    montoDoubleR = Double.parseDouble(montoR);
                    if (montoDoubleR < 1000) {
                        JOptionPane.showMessageDialog(null, "El valor a recargar debe ser de 1000 COP en adelante.");
                    } else {
                        restarSaldoPrincipal = saldoP - montoDoubleR;
                        numReg = up.modificarsaldo(usernameP, restarSaldoPrincipal);
                        numReg = up.insertarHistorial(usernameP, celular, idOperador, montoDoubleR);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
                if (numReg > 0) {
                    JOptionPane.showMessageDialog(null, "Recarga Exitosa");
                } else {
                    JOptionPane.showMessageDialog(null, "Error. No se pudo realizar la recarga.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error2.");
            }
        }
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void txtCuantoRCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuantoRCKeyTyped
        Procesos proc = new Procesos();
        proc.validarNumeros(evt);
    }//GEN-LAST:event_txtCuantoRCKeyTyped

    private void txtCuantoRCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuantoRCKeyReleased

    }//GEN-LAST:event_txtCuantoRCKeyReleased

    private void txtCuantoRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuantoRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuantoRCActionPerformed

    private void txtCelularRCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularRCKeyTyped
        Procesos proc = new Procesos();
        proc.validarNumeros(evt);
    }//GEN-LAST:event_txtCelularRCKeyTyped

    private void txtCelularRCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularRCKeyReleased

    }//GEN-LAST:event_txtCelularRCKeyReleased

    private void txtCelularRCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularRCKeyPressed

    }//GEN-LAST:event_txtCelularRCKeyPressed

    private void txtMontoRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoRKeyTyped
        Procesos proc = new Procesos();
        proc.validarNumeros(evt);
    }//GEN-LAST:event_txtMontoRKeyTyped

    private void txtMontoRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoRKeyReleased

    }//GEN-LAST:event_txtMontoRKeyReleased

    private void txtUsernameRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameRKeyTyped
        Procesos proc = new Procesos();
        proc.validarCaracteresNumeros(evt);
    }//GEN-LAST:event_txtUsernameRKeyTyped

    private void txtUsernameRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameRKeyReleased

    }//GEN-LAST:event_txtUsernameRKeyReleased

    private void btnEnviarDineroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEnviarDineroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarDineroKeyPressed

//--------------------------------------------------------------------
//     ******BOTON PARA ENVIAR O TRANSFERIR
//--------------------------------------------------------------------
    private void btnEnviarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarDineroActionPerformed
        //Variables
        boolean consultaSaldo = false;
        int numReg = 0;
        String usernameP, usernameR, montoR, mensaje = "";
        double montoDoubleR = 0, saldoInicial = 0, saldoInicialP = 0, saldoInicialR = 0, restarSaldoPrincipal = 0, sumarSaldoRecibe = 0;

        //Instancia usuario logeado principal
        var up = new Usuario();
        //Instancia usuario que recibe dinero enviado
        var ur = new Usuario();

        //User logeado envia $
        usernameP = txtUsernameP.getText();
        //User que recibe $
        usernameR = txtUsernameR.getText();
        //Variable montor para guardar
        montoR = txtMontoR.getText();
        //Var mensaje
        mensaje = txtAreaMensajeR.getText();

        if (txtUsernameR.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo usuario esta vacio, ingresa datos.");
        } else if (txtMontoR.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo monto esta vacio, ingresa datos. \n"
                + "y el valor a enviar debe ser de 5000 COP en adelante.");
        } else if (usernameP.equals(usernameR)) {
            JOptionPane.showMessageDialog(null, "No puedes enviar dinero a ti mismo.");
        } else {
            //Try para consultar el saldo de ambos usuarios
            try {
                //Saldo del usuario Princial que envia
                consultaSaldo = up.consultarSaldo(usernameP);
                //Saldo del que recibe
                consultaSaldo = ur.consultarSaldo(usernameR);
                //Primer IF
                if (consultaSaldo) {
                    //Saldo usu principal logeado
                    saldoInicialP = up.getSaldo();
                    //Saldo usu que recibe dinero
                    saldoInicialR = ur.getSaldo();

                    //parseo de saldo y proceso resta
                    try {
                        montoDoubleR = Double.parseDouble(montoR);
                        if (montoDoubleR < 5000) {
                            JOptionPane.showMessageDialog(null, "El valor a enviar debe ser de 5000 COP en adelante.");
                        } else {
                            restarSaldoPrincipal = saldoInicialP - montoDoubleR;
                            numReg = up.modificarsaldo(usernameP, restarSaldoPrincipal);
                            sumarSaldoRecibe = saldoInicialR + montoDoubleR;
                            numReg = ur.modificarsaldo(usernameR, sumarSaldoRecibe);
                            
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex);
                    }
                    //numReg > 0 o no
                    if (numReg > 0) {
                        JOptionPane.showMessageDialog(null, "Transferencia Exitosa");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error, no se realizo la transferencia.");
                    }
                    //if consultaSaldo usuario no existe
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario '" + usernameR + "' no existe.");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnEnviarDineroActionPerformed

    private void btnEnviarDineroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarDineroMouseClicked

    }//GEN-LAST:event_btnEnviarDineroMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblBotonPesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonPesoMouseClicked
        
    }//GEN-LAST:event_lblBotonPesoMouseClicked

    private void vacio() {
        JOptionPane.showMessageDialog(null, "Debe llenar los campos");
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnActua;
    public javax.swing.JButton btnEnviarDinero;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JComboBox<Operador> cmbOperadorRC;
    private javax.swing.JInternalFrame ifEnviarDinero;
    private javax.swing.JInternalFrame ifInformacion;
    private javax.swing.JInternalFrame ifOpciones;
    private javax.swing.JInternalFrame ifRecargarSM;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JLabel lblAvisoUsername;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblBienvenida2;
    private javax.swing.JLabel lblBotonPeso;
    private javax.swing.JLabel lblCelular;
    public javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblFranja;
    private javax.swing.JLabel lblLogoIcono;
    private javax.swing.JLabel lblMarranito;
    private javax.swing.JLabel lblMetas;
    private javax.swing.JLabel lblMsj;
    private javax.swing.JLabel lblMsj1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTabbedPane tbMenu;
    private javax.swing.JTabbedPane tbPrincipal;
    private javax.swing.JTextArea txtAreaMensajeR;
    public javax.swing.JTextField txtCelularRC;
    public javax.swing.JTextField txtCuantoRC;
    public javax.swing.JTextField txtMontoR;
    public javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtSaldoP;
    private javax.swing.JTextField txtUserBuscar;
    public javax.swing.JTextField txtUsernameP;
    public javax.swing.JTextField txtUsernameR;
    // End of variables declaration//GEN-END:variables

}
