package presentacion;

import java.awt.Desktop;
import java.io.IOException;
import java.sql.SQLException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import reglanegocio.TipoUsuario;
import reglanegocio.Estado;
import java.util.logging.Level;
import java.util.logging.Logger;
import reglanegocio.Usuario;

public class FrmUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        //cargarComboTipoUsuario();
        //cargarComboEstado();
    }
    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        btnLink1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnSalir1 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        cmbEstado = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtVerificacion = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 240, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 240, 10));

        jPanel6.setBackground(new java.awt.Color(0, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLink1.setBackground(new java.awt.Color(0, 102, 255));
        btnLink1.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        btnLink1.setForeground(new java.awt.Color(255, 255, 255));
        btnLink1.setText("Made with <3 by Leonardo Zuluaga");
        btnLink1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLink1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLink1ActionPerformed(evt);
            }
        });
        jPanel6.add(btnLink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 830, 40));

        jPanel7.setBackground(new java.awt.Color(0, 102, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Cascadia Mono", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CREAR USUARIO");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 830, 90));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(0, 204, 255));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel8MouseDragged(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir1.setBackground(new java.awt.Color(204, 0, 51));
        btnSalir1.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("X");
        btnSalir1.setBorder(null);
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 49, 33));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 840, -1));

        btnConsultar.setBackground(new java.awt.Color(0, 102, 255));
        btnConsultar.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 160, -1));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 255));
        btnActualizar.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 180, -1));

        btnCrear.setBackground(new java.awt.Color(0, 204, 51));
        btnCrear.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 140, -1));

        cmbEstado.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jPanel2.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 240, 30));

        txtNombre.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        txtNombre.setBorder(null);
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 240, -1));

        txtVerificacion.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        txtVerificacion.setBorder(null);
        jPanel2.add(txtVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 240, -1));

        txtPassword.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        txtPassword.setBorder(null);
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 240, -1));

        txtUsername.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        txtUsername.setBorder(null);
        jPanel2.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 240, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 240, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 51, 204));
        jSeparator4.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 240, 10));

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Username");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Verificacion");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tipo Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Estado");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        cmbTipoUsuario.setFont(new java.awt.Font("Cascadia Mono", 0, 24)); // NOI18N
        jPanel2.add(cmbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLink1ActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.leonardozuluaga.com.co"));
        } catch (URISyntaxException ex) {
            System.out.println(ex);
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnLink1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void jPanel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel8MouseDragged

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel8MousePressed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        boolean consulta = false;
        var u = new Usuario();
        String username = txtUsername.getText();

        if (username.equals("")) {
            JOptionPane.showMessageDialog(null, "Error al consultar, faltan datos");
        } else {

            try {
                consulta = u.consultar(username);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

            if (consulta) {
                txtPassword.setText(u.getPassword());
                txtVerificacion.setText(u.getPassword());
                txtNombre.setText(u.getNombre());
                try {
                    cmbTipoUsuario.removeAllItems();
                    cmbEstado.removeAllItems();
                    TipoUsuario.cargarCombo(cmbTipoUsuario, u.getIdTipoUsuario());
                    Estado.cargarCombo(cmbEstado, u.getIdEstado());
                } catch (SQLException ex) {
                    System.out.println(ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Usuario no encontrado");

            }

        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        int numReg = 0;
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String verificacion = txtVerificacion.getText();
        String nombre = txtNombre.getText();
        int idTipoUsuario = 0;
        int idEstado = 0;

        if ((cmbTipoUsuario.getSelectedIndex() != -1) && (cmbEstado.getSelectedIndex() != -1)) {
            idTipoUsuario = cmbTipoUsuario.getItemAt(cmbTipoUsuario.getSelectedIndex()).getId();
            idEstado = cmbEstado.getItemAt(cmbEstado.getSelectedIndex()).getId();
        }
        var u = new Usuario();

        if ("".equals(username) || "".equals(password) || "".equals(nombre) || (cmbTipoUsuario.getSelectedIndex() == -1) || (cmbEstado.getSelectedIndex() == -1)) {
            JOptionPane.showMessageDialog(null, "Error al Insertar, faltan datos");
        } else {

            try {
                numReg = u.modificar(username, password, nombre, idTipoUsuario, idEstado);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

            if (numReg > 0) {
                JOptionPane.showMessageDialog(null, "Usuario modificado");

            } else {
                JOptionPane.showMessageDialog(null, "Usuario no modificado");
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String verificacion = txtVerificacion.getText();
        String nombre = txtNombre.getText();
        int idTipoUsuario = 0;
        int idEstado = 0;

        if ((cmbTipoUsuario.getSelectedIndex() != -1) && (cmbEstado.getSelectedIndex() != -1)) {
            idTipoUsuario = cmbTipoUsuario.getItemAt(cmbTipoUsuario.getSelectedIndex()).getId();
            idEstado = cmbEstado.getItemAt(cmbEstado.getSelectedIndex()).getId();
        }
        int numReg = 0;
        var u = new Usuario();

        if ("".equals(username) || "".equals(password) || "".equals(nombre) || idTipoUsuario == 0 || idEstado == 0) {
            JOptionPane.showMessageDialog(null, "Error al Insertar, faltan datos");
        } else {
            try {
                numReg = u.insertar(username, password, nombre, idTipoUsuario, idEstado);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

            if (numReg > 0) {
                JOptionPane.showMessageDialog(null, "Usuario insertado");

            } else {
                JOptionPane.showMessageDialog(null, "Usuario no insertado");
            }
        }
        //int vId = cmbTipoUsuario.getItemAt(cmbTipoUsuario.getSelectedIndex()).getId();
        //JOptionPane.showMessageDialog(null, ""+vId);
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnLink1;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<Estado> cmbEstado;
    private javax.swing.JComboBox<TipoUsuario> cmbTipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtVerificacion;
    // End of variables declaration//GEN-END:variables
}
